language: php
php:
  - '5.5'
  - '5.6'
  - '7.0'
 env:
  - MIN_PHP_VERSION=5.5
  - CONFIG_DIR=config
  - AUTOLOAD_DIR=classes
  - AUTOLOAD_EXTS=.php
  - AUTOLOAD_FUNC=spl_autoload
script: php unit.php
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/9d085552b0f8d863b23c
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
