<?php
if (PHP_SAPI !== 'cli') {
	http_response_code(403);
	exit();
}
if (! function_exists('php_check_syntax')) {
	/**
	 * Check the PHP syntax of (and execute) the specified file
	 *
	 * @param  string $filename      The name of the file being checked.
	 * @param  string $error_message The error message generated by the syntax check. (by reference)
	 * @return bool                  Returns TRUE if the lint check passed, and FALSE if the link check failed
	 */
	function php_check_syntax($filename, &$error_message)
	{
		$out = [];
		$error_message = exec(sprintf('php -l %s', escapeshellarg($filename)), $out, $return_var);
		return $return_var !== false;
	}
}

// Do a syntax check on each PHP script in DocumentRoot directory
foreach (glob('*.php') as $script) {
	$clean_syntax = php_check_syntax('index.php', $syntax_errors);
	assert($clean_syntax, $syntax_errors . __FILE__);
	unset($script, $clean_syntax, $syntax_errors);
}

// Require the autoloader and check it
require_once(getenv('AUTOLOAD_SCRIPT'));
assert('class_exists("\shgysk8zer0\Core\Timer")', 'Autoloader mis-configured');
